[package]
name = "agglayer-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pessimistic-proof = { path = "../pessimistic-proof" }

ethers-signers = { workspace = true, optional = true }
hex.workspace = true
reth-primitives.workspace = true
serde.workspace = true
serde_with.workspace = true
sp1-sdk.workspace = true
sp1-core-machine.workspace = true
thiserror.workspace = true
bincode.workspace = true

[dev-dependencies]
ethers-signers.workspace = true

[features]
default = []
testutils = ["ethers-signers"]
