[package]
name = "pessimistic-proof-program"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bincode = "1.3.3"
pessimistic-proof = { path = "../pessimistic-proof" }
sp1-zkvm = "1.1.1"
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }

[build-dependencies]
sp1-cli = "1.1.1"

[patch.crates-io]
tiny-keccak = { git = "https://github.com/0xPolygonHermez/tiny-keccak", branch = "edu/zisk" }