[package]
name = "pessimistic-proof-program"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bincode = "1.3.3"
pessimistic-proof = { path = "../pessimistic-proof" }
sp1-zkvm = { version = "3.3.0" }

[build-dependencies]
sp1-cli = "3.3.0"
