[package]
name = "pessimistic-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives.workspace = true
bincode.workspace = true
hex.workspace = true
tracing.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
serde_with = { version = "3" }
thiserror.workspace = true
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2", features = [
    "keccak",
] }
sp1-zkvm = { version = "3.3.0", features = ["verify"] }
sp1-sdk = "3.3.0"
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes.git", package = "sha2", branch = "patch-v0.10.8" }

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4"
rs_merkle = { version = "1.4", default-features = false }
rand = "0.8.5"
