[package]
name = "agglayer"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "env", "string"] }
dirs.workspace = true
dotenvy.workspace = true
toml.workspace = true

agglayer-node = { path = "../agglayer-node" }
agglayer-prover = { path = "../agglayer-prover" }
agglayer-config = { path = "../agglayer-config" }

[dev-dependencies]
assert_cmd = "2.0.14"
clap-doc = "0.1.0"
expect-test = "1.5.0"
insta.workspace = true
trycmd = "0.15.8"
